# Conclusion

Working on this project was very interesting and informative as it gave us the opportunity to discover the patterns of the MTA ridership across different modes at such a pivotal point in time. What we found to be very interesting was the high correlation between the different modes of transportation as well as the similarity in ridership regardless of the season and or day of the week- this is truly the city that never sleeps. In regards to the data, there were a good amount of times where there has to be transformations in order to interpret it properly and then visualize it.

In the future we will be sure to look into additional datasets to broaden the scope of the analysis and uncover more hidden patterns and behaviors over time as a result of the economy, policy, additions and/or removals of routes or transportation modes. It would be very interesting to see how or if the current trends keep going in the same direction and at what speed, magnitude and for how long? These are just a few questions we would love to know about in addition to what we have now.